### PR TITLE
Autoformat all files according to the `.editorconfig` settings

### PR DESCRIPTION
**Pull request by oliverklee**
This autoformatting has been done with PhpStorm.

The PHP files probably still are not PSR-12 compliant. (This will come
in a later change.)

### CODE REVIEW

**Comment by oliverklee** [comment]
Hold on, I think Markdown should have lines no longer than 80 characters. I'll do some more research on best practices there.

**Comment by Danon** [comment]
Hello! Thanks for the update!

Do you think we can keep some of the settings I had there? Most notably:
- No blank line before the namespace
- A little longer hard-wrap?

**Comment by oliverklee** [comment]
I think I'll go another way and reformat the PHP files using PHP_CodeSniffer with the PSR-12 ruleset. I'll do that in another PR.

**Comment by Danon** [comment]
Ok, my point from before "No blank line before the namespace", ignore that. It will make sense when we add `declare(strict_types=1)`.

**Comment by Danon** [comment]
@oliverklee Is this still a draft or should be closed?

**Comment by oliverklee** [comment]
Let's close this. Thanks for the ping, @Danon!

**Pull request closed without merging**
