### PR TITLE
Autoformat all PHP files with PhpStorm

### PR DESCRIPTION
**Pull request by oliverklee**
This allows contributors to autoformat their changed files without
risking to also affect the unchanged code.

This change hopefully also makes the code a bit nicer to read.

### CODE REVIEW

**Comment by Danon** [comment]
I like the changes, but there was a reason why values in file ArrayMatrixTest.php  were formatted the certain way.

The order of the keys and values in the array displayed very nicely what the matrix was being build. Now with this linear formatting in ArrayMatrixTest.php, it's not so clear.

**Comment by oliverklee** [comment]
Would it help if I added a blank lines where the file previously had line breaks?

**Comment by Danon** [comment]
@oliverklee Yes, and remove comments `// 1`, `// A`, and `// red`. They're useless now.

**Comment by oliverklee** [comment]
Done and repushed.

**Pull request merged**
