### PR TITLE
Add PHP_CodeSniffer to the CI build

### LINKED ISSUE #38: Add the code sniffer to the CI builds

### PR DESCRIPTION
**Pull request by oliverklee**
Fixes #38

### CODE REVIEW

**Comment by oliverklee** [comment]
Blocked by #40.

**Comment by Danon** [comment]
Can we not add another job for that, but piggy pack over the existing `unit-tests` job? 

We should rename it to `formal-rules` or something similar.

**Comment by oliverklee** [comment]
> Can we not add another job for that, but piggy pack over the existing `unit-tests` job?

I'd prefer not to - it would be a bit dirty, and I like being able to see whether the PHP is invalid (i.e., the PHP linter job fails), the PHP does not work correctly (i.e., the unit tests fail), or the PHP is not well-styled (i.e., PHP_CodeSniffer fails).

In addition, we want to run the linter and the unit tests with each supported PHP version, while we need the stylecheck only once.

**Comment by oliverklee** [comment]
(In general, the approach of GitHub Actions is more in the direction of multiple, smaller, mostly independent jobs, while Travis CI went more the "one big job" approach.)

**Comment by Danon** [comment]
Ok

**Comment by Danon** [comment]
Is it everything from Project https://github.com/T-Regx/CrossDataProviders/projects/1 ? :)

**Comment by oliverklee** [comment]
> Is it everything from Project https://github.com/T-Regx/CrossDataProviders/projects/1 ? :)

Yes, it is! :tada: I've closed the project now.

**Pull request merged**
