### PR TITLE
Add void return type declarations

### PR DESCRIPTION
**Pull request by oliverklee**
This is required for making the code base fully typed.

Also add some `@throws` annotations.

### CODE REVIEW

**Comment by Danon** [comment]
In test methods? We never call these methods from the code, so what's the point? 

Additionally, It will make it slightly more annoying to copy and paste data providers and not all tests have phpDoc in them, some methods start with `test()`, and they don't need `@test` annotation.

**Comment by oliverklee** [comment]
I've now split this up, with #49 covering the changes in `src/`.

**Comment by Danon** [comment]
#39 merged.

I'm sorry, but I don't see any added value from typing the test methods. If we resign from PHP 7.0 compatibility, I will gladly add `: void` typehint, but in the annotation, that I use only for `@test` and `@dataProvider`, I find it distracting and unncecesary.

**Comment by oliverklee** [comment]
Okay, then let's postpone this until we require PHP >= 7.1. (We have lots of PHPStan levels to work with before PHPStan requires all arguments and return values to have a type declaration/annotation anyway. :-) (This starts [at level 6](https://phpstan.org/user-guide/rule-levels), and we're currently at level 0.))

**Comment by Danon** [comment]
Yes, good idea.

**Comment by Danon** [comment]
I added the `postponed` label

**Comment by Danon** [comment]
@oliverklee Do you think we should resign from PHP 7.0 compatiblity now/soon-ish?

**Comment by Danon** [comment]
> > @oliverklee Do you think we should resign from PHP 7.0 compatibility now/soon-ish?
> 
> Yes - I'd be fine with dropping PHP 7.0 compatibility right now.

So we'll use `: void` PHP 7.1 type hints, instead of `@void` annotations, correct? :)

**Comment by oliverklee** [comment]
Yes, that's correct. (I propose to have three separate PRs: one for changing the version requirement, one (this one) for adding the `void` return type annotations (and converting the existing ones), and one for using all the other PHP 7.1 goodness.)

**Comment by Danon** [comment]
@oliverklee Dibs on the version requirement ;)

**Comment by Danon** [comment]
Okey. So now we can just use `: void` type hints, instead of the `@void` comments.

**Pull request merged**
